### ISSUE TITLE
Dashboard Page: Monthly Benefit styling

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/SSWHEN#113]
## Description
On DashboardPage within the segments, the `Monthly` header.

## Expected Behavior
`Monthly` header should be left aligned.

## Actual Behavior
`Monthly` header is center aligned.

**Comment by jorduno19** [comment]
addressed in https://github.com/SoftStackFactory/SSWHEN/pull/123

**Comment by khoadnguyen** [comment]
This has been reviewed.
