### ISSUE TITLE
Issues - morning of 02/28/18

### ISSUE THREAD

**Issue by Abdul-Sayed** [SoftStackFactory/SSWHEN#91]
1) The Results Page won't populate the charts or table

2) Registration Page keeps logging Unsuccessful registration, even after many attempts of valid form inputs

These issues were not present last night

Anyone else aware of these ?

**Comment by Natalied9** [comment]
Had the same issues, but these are both working for me with most recent develop about an hour ago

**Comment by khoadnguyen** [comment]
Older issue, this was resolved.
